import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext, ttk
import subprocess, os, time
from datetime import datetime

# =========================================================
# Safe parser for cis_results.tmp
# =========================================================
def parse_results(filepath):
    findings = []
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split(";")
                entry = {}
                for part in parts:
                    if "=" in part:
                        k, v = part.split("=", 1)
                        entry[k.strip()] = v.strip()
                if entry:
                    findings.append(entry)
    except Exception as e:
        print(f"[!] Parse error: {e}")
    return findings

# =========================================================
# Generate HTML report
# =========================================================
def generate_html(findings, output_html):
    report_dir = os.path.dirname(output_html)
    os.makedirs(report_dir, exist_ok=True)
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>CIS FortiGate 7.0.x Compliance Report</title>
<style>
body{{font-family:Segoe UI,Arial,sans-serif;background:#fafafa;color:#222;margin:20px;}}
h1{{color:#0056b3;text-align:center;}}
table{{border-collapse:collapse;width:100%;margin-top:15px;box-shadow:0 2px 4px rgba(0,0,0,0.1);}}
th,td{{border:1px solid #ddd;padding:8px;text-align:left;vertical-align:top;}}
th{{background:#0056b3;color:#fff;}}
tr:nth-child(even){{background:#f2f2f2;}}
.pass{{color:green;font-weight:bold;}}
.fail{{color:red;font-weight:bold;}}
.manual{{color:orange;font-weight:bold;}}
footer{{text-align:center;color:#777;margin-top:25px;font-size:12px;}}
</style>
</head><body>
<h1>CIS FortiGate 7.0.x Compliance Report</h1>
<p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
<table>
<tr><th>ID</th><th>Title</th><th>Risk</th><th>Status</th><th>Fix Type</th><th>Description</th><th>Remediation</th></tr>
"""
    for f in findings:
        sid = f.get("FINDING_ID","N/A")
        title = f.get("TITLE","N/A")
        risk = f.get("RISK","N/A")
        status = f.get("STATUS","N/A")
        fix = f.get("FIX_TYPE","N/A")
        desc = f.get("DESCRIPTION","N/A")
        rem = f.get("REMEDIATION","N/A")
        cls = {"Pass":"pass","Fail":"fail","Manual":"manual"}.get(status,"")
        html += f"<tr><td>{sid}</td><td>{title}</td><td>{risk}</td><td class='{cls}'>{status}</td><td>{fix}</td><td>{desc}</td><td>{rem}</td></tr>\n"
    html += "</table><footer>FortiGate CIS Audit — Automated Report</footer></body></html>"
    with open(output_html,"w",encoding="utf-8") as f:
        f.write(html)
    print(f"[✔] HTML report saved: {output_html}")

# =========================================================
# Run CIS checks
# =========================================================
def run_checks(cfg, status_text, progress, summary_labels):
    start = time.time()
    temp_out = os.path.join(os.getenv("TEMP","/tmp"),"cis_results.tmp")
    script_dir = os.path.dirname(os.path.abspath(__file__))
    report_dir = os.path.join(script_dir,"reports")
    os.makedirs(report_dir,exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_html = os.path.join(report_dir,f"cis_report_{ts}.html")
    bash = r"C:\Program Files\Git\bin\bash.exe" if os.name=="nt" else "bash"
    cmd = [bash, os.path.join(script_dir,"cis_check.sh"), cfg, temp_out]

    status_text.delete(1.0,tk.END)
    status_text.insert(tk.END,f"Running command: {' '.join(cmd)}\n\n","info")
    status_text.update()

    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    while proc.poll() is None:
        time.sleep(0.3)
        progress.step(2)
        root.update_idletasks()
    out, err = proc.communicate()
    status_text.insert(tk.END,out,"info")
    if err:
        status_text.insert(tk.END,err,"error")

    if not os.path.exists(temp_out):
        messagebox.showerror("Error","No output generated by cis_check.sh")
        return

    findings = parse_results(temp_out)
    generate_html(findings,out_html)

    total = len(findings)
    passed = sum(1 for f in findings if f.get("STATUS")=="Pass")
    failed = sum(1 for f in findings if f.get("STATUS")=="Fail")
    manual = total - passed - failed
    t = time.time()-start
    fs = os.path.getsize(cfg)/1024

    status_text.insert(tk.END,f"\nFile: {cfg} ({fs:.1f} KB)\nExecution: {t:.2f}s\n","info")
    status_text.insert(tk.END,f"Summary: {total} checks — Pass {passed}, Fail {failed}, Manual {manual}\n","info")
    status_text.insert(tk.END,f"Report: {out_html}\n","pass")

    summary_labels["pass"]["text"]=f"Pass: {passed}"
    summary_labels["fail"]["text"]=f"Fail: {failed}"
    summary_labels["manual"]["text"]=f"Manual: {manual}"

    progress.stop()
    try: os.remove(temp_out)
    except: pass

# =========================================================
# GUI setup
# =========================================================
root=tk.Tk()
root.title("CIS FortiGate 7.0.x Compliance Checker")
root.geometry("900x700")
root.configure(bg="#eef2f5")

style=ttk.Style()
style.configure("TButton",font=("Arial",10),padding=6)
style.configure("TLabelframe",background="#eef2f5")
style.configure("Banner.TLabel",font=("Arial",16,"bold"),background="#004080",foreground="white",padding=10)

banner=ttk.Label(root,text="CIS FortiGate 7.0.x Compliance Checker",style="Banner.TLabel")
banner.pack(fill="x",pady=5)

ttk.Label(root,text="Select FortiGate Configuration File:",background="#eef2f5",font=("Arial",12)).pack(pady=10)

button_frame=tk.Frame(root,bg="#eef2f5")
button_frame.pack()

def choose_file():
    f=filedialog.askopenfilename(title="Select Config File")
    if f:
        progress.start(10)
        run_checks(f,status_text,progress,summary_labels)

ttk.Button(button_frame,text="Browse & Run",command=choose_file).grid(row=0,column=0,padx=6)
ttk.Button(button_frame,text="Clear",command=lambda:status_text.delete(1.0,tk.END)).grid(row=0,column=1,padx=6)

# Progress bar
progress=ttk.Progressbar(root,length=600,mode="indeterminate")
progress.pack(pady=10)

# Status output
status_text=scrolledtext.ScrolledText(root,height=20,width=110,bg="white",fg="#222",font=("Consolas",10))
status_text.pack(padx=10,pady=10)

status_text.tag_config("info",foreground="#000")
status_text.tag_config("error",foreground="red")
status_text.tag_config("pass",foreground="green",font=("Consolas",10,"bold"))

# Summary bar
summary_frame=ttk.LabelFrame(root,text="Summary",padding=10)
summary_frame.pack(fill="x",pady=8)
summary_labels={
    "pass":ttk.Label(summary_frame,text="Pass: 0",foreground="green",font=("Arial",11,"bold")),
    "fail":ttk.Label(summary_frame,text="Fail: 0",foreground="red",font=("Arial",11,"bold")),
    "manual":ttk.Label(summary_frame,text="Manual: 0",foreground="orange",font=("Arial",11,"bold")),
}
summary_labels["pass"].pack(side="left",padx=15)
summary_labels["fail"].pack(side="left",padx=15)
summary_labels["manual"].pack(side="left",padx=15)

root.mainloop()
